"""Create tables

Revision ID: 2635afa4c8a0
Revises: 
Create Date: 2025-06-09 22:21:04.321570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2635afa4c8a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diem_thi',
    sa.Column('sbd', sa.String(), nullable=False),
    sa.Column('toan', sa.Float(), nullable=True),
    sa.Column('ngu_van', sa.Float(), nullable=True),
    sa.Column('ngoai_ngu', sa.Float(), nullable=True),
    sa.Column('vat_li', sa.Float(), nullable=True),
    sa.Column('hoa_hoc', sa.Float(), nullable=True),
    sa.Column('sinh_hoc', sa.Float(), nullable=True),
    sa.Column('lich_su', sa.Float(), nullable=True),
    sa.Column('dia_li', sa.Float(), nullable=True),
    sa.Column('gdcd', sa.Float(), nullable=True),
    sa.Column('ma_ngoai_ngu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sbd')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diem_thi')
    # ### end Alembic commands ###
